"""
report_generator.py
Generates a professional PDF audit report from all module outputs.
"""

from fpdf import FPDF
import datetime
import os


class AuditReportPDF(FPDF):
    def __init__(self, title="Fairscope Bias Audit Report"):
        super().__init__()
        self.report_title = title
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(30, 30, 30)
        self.cell(0, 8, 'FAIRSCOPE - AI FAIRNESS AUDIT REPORT', align='L')
        self.set_font('Helvetica', '', 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, f'Page {self.page_no()}', align='R', new_x='LMARGIN', new_y='NEXT')
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Generated by Fairscope | {datetime.datetime.now().strftime("%Y-%m-%d %H:%M UTC")} | CONFIDENTIAL - INTERNAL AUDIT USE ONLY', align='C')

    def section_title(self, title: str):
        self.ln(6)
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(15, 40, 80)
        self.set_fill_color(240, 244, 252)
        self.cell(0, 9, f'  {title}', fill=True, new_x='LMARGIN', new_y='NEXT')
        self.ln(3)

    def subsection_title(self, title: str):
        self.ln(3)
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(50, 50, 50)
        self.cell(0, 7, title, new_x='LMARGIN', new_y='NEXT')
        self.ln(1)

    def body_text(self, text: str, indent: int = 0):
        self.set_font('Helvetica', '', 9)
        self.set_text_color(60, 60, 60)
        self.set_x(10 + indent)
        self.multi_cell(190 - indent, 5, str(text), new_x='LMARGIN', new_y='NEXT')
        self.ln(1)

    def metric_row(self, label: str, value: str, status: str = ""):
        self.set_font('Helvetica', '', 9)
        self.set_text_color(60, 60, 60)

        status_colors = {
            'PASS': (0, 150, 80),
            'FAIL': (200, 40, 40),
            'WARNING': (200, 130, 0),
            'HIGH': (200, 40, 40),
            'MEDIUM': (200, 130, 0),
            'LOW': (0, 150, 80),
        }

        self.cell(100, 6, label)
        self.cell(50, 6, value)
        if status and status in status_colors:
            r, g, b = status_colors[status]
            self.set_font('Helvetica', 'B', 9)
            self.set_text_color(r, g, b)
            self.cell(40, 6, status)
            self.set_text_color(60, 60, 60)
            self.set_font('Helvetica', '', 9)
        self.ln()

    def divider(self):
        self.set_draw_color(220, 220, 220)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(5)


def generate_audit_report(
    domain: str,
    sensitive_cols: list,
    target_col: str,
    sensitivity_results: dict,
    fairness_results: dict,
    blackbox_results: dict,
    chosen_metric: str,
    gemini_rationale: str,
    gemini_summary: str,
    output_path: str = "fairscope_audit_report.pdf"
) -> str:
    pdf = AuditReportPDF()
    pdf.add_page()

    # Cover section
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(15, 40, 80)
    pdf.ln(8)
    pdf.cell(0, 12, 'FAIRSCOPE', align='C', new_x='LMARGIN', new_y='NEXT')
    pdf.set_font('Helvetica', '', 13)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, 'AI Fairness Audit Report', align='C', new_x='LMARGIN', new_y='NEXT')
    pdf.ln(6)

    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(120, 120, 120)
    now = datetime.datetime.utcnow()
    pdf.cell(0, 6, f'Generated: {now.strftime("%B %d, %Y at %H:%M UTC")}', align='C', new_x='LMARGIN', new_y='NEXT')
    pdf.cell(0, 6, f'Domain: {domain.title()}  |  Target: {target_col}  |  Sensitive Attributes: {", ".join(sensitive_cols)}', align='C', new_x='LMARGIN', new_y='NEXT')
    pdf.ln(8)

    # Executive Summary
    pdf.section_title('EXECUTIVE SUMMARY')
    if gemini_summary:
        pdf.body_text(gemini_summary)
    else:
        high_count = sensitivity_results.get('high_risk_count', 0)
        medium_count = sensitivity_results.get('medium_risk_count', 0)
        pdf.body_text(
            f"This audit analyzed automated decision-making in the {domain} domain. "
            f"Analysis identified {high_count} high-risk and {medium_count} medium-risk proxy features. "
            f"The organization has selected '{chosen_metric}' as the primary fairness criterion. "
            f"Findings are documented below with statistical, moral, and legal justifications."
        )

    pdf.ln(2)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_text_color(50, 50, 50)
    overall_bias = blackbox_results.get('overall_bias_detected', False) if blackbox_results else False
    pdf.cell(0, 6, f'Overall Bias Risk Assessment: {"HIGH RISK - Bias Detected" if overall_bias else "MODERATE - Proceed with Monitoring"}')
    pdf.ln(8)

    # Module 1: Sensitivity Analysis
    pdf.section_title('MODULE 1: ATTRIBUTE SENSITIVITY ANALYSIS')
    pdf.body_text(
        'The Attribute Sensitivity Scorer evaluates each non-sensitive feature for its statistical '
        'relationship with the outcome variable and its potential to serve as a proxy for sensitive '
        'attributes. Mutual information and surrogate model scores are combined into a composite risk index.'
    )

    risk_df = sensitivity_results.get('risk_dataframe', None)
    if risk_df is not None and len(risk_df) > 0:
        pdf.subsection_title('Feature Risk Rankings (Top 10)')
        pdf.set_font('Helvetica', 'B', 8)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(50, 6, 'Feature', border='B')
        pdf.cell(35, 6, 'MI (Outcome)', border='B')
        pdf.cell(35, 6, 'Proxy MI', border='B')
        pdf.cell(35, 6, 'Composite Score', border='B')
        pdf.cell(25, 6, 'Risk', border='B')
        pdf.ln()

        top_features = risk_df.head(10)
        for _, row in top_features.iterrows():
            pdf.set_font('Helvetica', '', 8)
            pdf.set_text_color(60, 60, 60)
            risk_colors = {'HIGH': (200, 40, 40), 'MEDIUM': (200, 130, 0), 'LOW': (0, 150, 80)}
            r, g, b = risk_colors.get(row['risk_tier'], (60, 60, 60))

            pdf.cell(50, 5, str(row['feature'])[:22])
            pdf.cell(35, 5, str(row['mi_with_outcome']))
            pdf.cell(35, 5, str(row['max_proxy_mi']))
            pdf.cell(35, 5, str(row['composite_risk_score']))
            pdf.set_text_color(r, g, b)
            pdf.set_font('Helvetica', 'B', 8)
            pdf.cell(25, 5, str(row['risk_tier']))
            pdf.ln()
            pdf.set_text_color(60, 60, 60)
            pdf.set_font('Helvetica', '', 8)

    # Intersectional risks
    intersectional = sensitivity_results.get('intersectional_risks', [])
    if intersectional:
        pdf.ln(4)
        pdf.subsection_title('Intersectional Blind Spot Detection')
        pdf.body_text(
            'The following feature combinations exhibit synergistic proxy effects -- '
            'appearing safe individually but revealing sensitive attribute information in combination.'
        )
        for risk in intersectional[:3]:
            pdf.set_font('Helvetica', '', 9)
            label = f"  {risk['feature_1']} x {risk['feature_2']} -> proxy for {risk['sensitive_attr']}"
            pdf.cell(0, 5, label, new_x='LMARGIN', new_y='NEXT')
            pdf.set_text_color(150, 150, 150)
            pdf.cell(0, 5, f"    Synergy Score: {risk['synergy_score']}  |  Blind Spot: {'Yes' if risk.get('blind_spot') else 'No'}", new_x='LMARGIN', new_y='NEXT')
            pdf.set_text_color(60, 60, 60)

    # Module 2: Fairness Metrics
    pdf.section_title('MODULE 2: FAIRNESS METRICS AND CONFLICT ANALYSIS')

    if fairness_results:
        pdf.metric_row('Overall Model Accuracy', f"{fairness_results.get('overall_accuracy', 0)*100:.1f}%", '')
        pdf.metric_row('Overall AUC-ROC', f"{fairness_results.get('overall_auc', 0):.4f}", '')
        pdf.metric_row('Sensitive Attribute Analyzed', str(fairness_results.get('sensitive_col', '')), '')
        pdf.metric_row('Privileged Group', str(fairness_results.get('privileged_group', '')), '')
        pdf.ln(2)

        pdf.subsection_title('Fairness Metrics Summary')
        agg = fairness_results.get('aggregate_metrics', {})
        # Standard thresholds for each metric
        thresholds = {
            'demographic_parity_difference': 0.10,
            'equalized_odds_difference': 0.10,
            'equal_opportunity_difference': 0.10,
            'predictive_parity_difference': 0.10,
            'calibration_difference': 0.05,
        }

        for metric, val in agg.items():
            thresh = thresholds.get(metric, 0.1)
            status = 'PASS' if abs(val) <= thresh else 'FAIL'
            pdf.metric_row(metric.replace('_', ' ').title(), f"{val:.4f}", status)

        conflicts = fairness_results.get('detected_conflicts', [])
        if conflicts:
            pdf.ln(3)
            pdf.subsection_title('Detected Fairness Conflicts')
            for c in conflicts:
                pdf.set_font('Helvetica', 'B', 9)
                pdf.set_text_color(180, 40, 40)
                pdf.cell(0, 6, f"  [{c['conflict_type']}] {c['metric_1'].replace('_',' ')} vs {c['metric_2'].replace('_',' ')}", new_x='LMARGIN', new_y='NEXT')
                pdf.set_font('Helvetica', '', 8)
                pdf.set_text_color(80, 80, 80)
                pdf.body_text(f"  {c['description']}", indent=5)
                pdf.set_text_color(60, 60, 60)

        # Chosen metric and rationale
        pdf.ln(3)
        pdf.subsection_title(f'Selected Fairness Criterion: {chosen_metric}')
        if gemini_rationale:
            pdf.body_text(gemini_rationale)

    # Module 3: Black-Box Probe
    pdf.section_title('MODULE 3: BLACK-BOX COUNTERFACTUAL PROBE')
    pdf.body_text(
        'Counterfactual testing systematically alters proxy features to detect whether '
        'the model produces different outcomes for otherwise identical profiles. '
        'This method audits the model without requiring access to internal weights or architecture.'
    )

    if blackbox_results:
        pdf.metric_row(
            'Total Counterfactual Tests Run',
            str(blackbox_results.get('total_tests_run', 0)), ''
        )
        pdf.metric_row(
            'Combined Proxy Bias Rate',
            f"{blackbox_results.get('combined_bias_rate', 0)*100:.1f}%",
            'HIGH' if blackbox_results.get('combined_bias_rate', 0) > 0.15 else 'PASS'
        )
        pdf.metric_row(
            'Mean Probability Shift (Combined)',
            f"{blackbox_results.get('combined_mean_prob_delta', 0):.4f}", ''
        )
        pdf.metric_row(
            'Overall Bias Assessment',
            'Bias Detected' if blackbox_results.get('overall_bias_detected') else 'No Significant Bias',
            'FAIL' if blackbox_results.get('overall_bias_detected') else 'PASS'
        )

        feat_summary = blackbox_results.get('feature_impact_summary', {})
        if feat_summary:
            pdf.ln(3)
            pdf.subsection_title('Per-Feature Bias Impact')
            for feat, summary in feat_summary.items():
                status = 'FAIL' if summary.get('bias_detected') else 'PASS'
                pdf.metric_row(
                    feat,
                    f"Change Rate: {summary['outcome_change_rate']*100:.1f}% | Delta: {summary['mean_prob_delta']:.4f}",
                    status
                )

    # Legal Context
    pdf.section_title('APPLICABLE LEGAL FRAMEWORK')
    legal_context = sensitivity_results.get('legal_context', {})
    laws = legal_context.get('laws', [])
    protected = legal_context.get('protected_classes', [])

    if laws:
        pdf.subsection_title('Applicable Regulations')
        for law in laws:
            pdf.body_text(f"  - {law}", indent=3)

    if protected:
        pdf.subsection_title('Protected Classes in This Domain')
        pdf.body_text(', '.join(protected))

    # Disclaimer
    pdf.section_title('DISCLAIMER AND LIMITATIONS')
    pdf.body_text(
        'This report was generated by Fairscope, an automated AI fairness auditing tool. '
        'Portions of the narrative analysis were generated using Google Gemini (large language model) '
        'and may not reflect legal advice. Legal citations should be independently verified. '
        'This report does not constitute legal counsel. Organizations should consult qualified legal '
        'and technical experts before making compliance decisions. Fairscope does not guarantee '
        'that adherence to any single fairness metric eliminates discriminatory outcomes.'
    )

    pdf.body_text(
        f'Audit Timestamp: {now.strftime("%Y-%m-%dT%H:%M:%SZ")}  |  '
        f'Fairscope Version: 1.0.0-MVP  |  '
        f'Model: Google Gemini 1.5 Flash (narrative generation)'
    )

    # Save
    pdf.output(output_path)
    return output_path
